spring:
  mvc:
    throw-exception-if-no-handler-found: true
    view:
      prefix: /
      suffix: .html
  resources:
    add-mappings: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ENC(7zovvVtLBhESyS5AHsxrPw==)
    url: jdbc:mysql://localhost:3308/vDataBase
  servlet:
    multipart:
      max-file-size: 10MB
logging:
  level:
    com.vurtne.side.mapper : debug


tx-oss:
  app-id: ENC(FTUq82SIkTQzsVy4Ctk681+nROVk0ZRn)
  secret-id: ENC(2I9KgyJ7YahwyWKFrSSF/pQlYyQrafteraXy2EEdQnrxxccBA7lhQu1P7UaWFZXQ)
  secret-key: ENC(8xHLrtezH/tku0kipaJAuwfpQyE/bdXWRae3jE1LAQKg8WedtwGh9QQFE4hifBEc)
  bucket-name: ENC(xPptrMKFERmY/ShyqrlD3kyZtYmWMFoqRrwq3JxT56s=)
jasypt:
  encryptor:
    password: ${my_salt}
