spring:
  mvc:
    throw-exception-if-no-handler-found: true
    view:
      prefix: /
      suffix: .html
  resources:
    add-mappings: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3308/vDataBase
  servlet:
    multipart:
      max-file-size: 10MB
logging:
  level:
    com.vurtne.side.mapper : debug


tx-oss:
  app-id: 1252864727
  secret-id: AKIDU1cGvShaCh9dCnsdGmATdq4JQo377Yel
  secret-key: AGKEziJl8fAzmcL7jCXvOtGUZVK3cwGf
  bucket-name: vurtne-1252864727
jasypt:
  encryptor:
    password: xxx